import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const [status, setStatus] = useState(false);
  // useEffect(() => {
  //   if (localStorage.getItem("accessToken") == null) {
  //     setStatus(false);
  //   } else {
  //     setStatus(true);
  //   }
  // }, []);

  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
